logspout:
  labels:
    # Pull all containers again  
    io.rancher.container.pull_image: always
    # Deploy container to all hosts
    io.rancher.scheduler.global: true
  image: gliderlabs/logspout
  volumes:
  - /var/run/docker.sock:/tmp/docker.sock
  container_name: logspout
  # Replace the X's with the appropriate details.
  command: "syslog://logsX.papertrailapp.com:XXXXX" 
  
  # Make sure that all containers do not start with "tty: true" from docker-compose 
  # and "-t" from docker run commands.
